FROM matzhaugen/concord-builder:1 as builder
COPY . /io
WORKDIR /io
ENV PLAT=manylinux2014_x86_64
# Install concord

RUN travis/build_wheels.sh

# FROM python:3.8-slim
# COPY --from=builder /io/wheelhouse /wheelhouse

