FROM python:3.8
COPY . pyccista
WORKDIR pyccista
RUN pip install numpy && python -m pip install --upgrade twine
# Install concord
RUN apt update && apt -y install wget && \
	wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.gz && \
	tar -xzvf 3.3.7.tar.gz
RUN wget http://prdownloads.sourceforge.net/swig/swig-4.0.2.tar.gz &&\
	tar -xzvf swig-4.0.2.tar.gz &&\
	cd swig-4.0.2 && ./configure && make && make install

RUN python setup.py build_ext -I eigen-eigen-323c052e1731/ install sdist bdist_wheel
	# python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
	# pip install -i https://test.pypi.org/simple/ pyconcord==0.1
	#  \
	# rm 3.3.7.tar.gz && rm -rf eigen-eigen-323c052e1731/ &&\
	# rm -rf build && \
	# apt -y remove wget