[tox]
requires =
    tox>=4
    setuptools >= 74.1.2
env_list = py{310}

[testenv]
description = run unit tests
deps =
    pytest>=7
    scikit-learn
    pytest-sugar
commands =
    pytest {posargs:tests}